spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  jackson:
    serialization.indent_output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/vacancy;DB_CLOSE_DELAY=-1
    username: vacancy
    password:
    hikari:
      auto-commit: false
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.generate_statistics: true

server:
  port: @server.port@
